name: Deploy Azure Infrastructure

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: write

env:
  RESOURCE_GROUP: acmetickets_rg
  CONTAINERAPPS_ENVIRONMENT: acmeticketsacadev
  AZURE_LOCATION: eastus2
  SERVICEBUS_NAMESPACE: acmeticketsasb

jobs:
  deploy-shared-infra:
    runs-on: ubuntu-latest
    outputs:
      resource_group: ${{ steps.set-outputs.outputs.resource_group }}
      containerapps_env: ${{ steps.set-outputs.outputs.containerapps_env }}
      azure_location: ${{ steps.set-outputs.outputs.azure_location }}
      servicebus_namespace: ${{ steps.set-outputs.outputs.servicebus_namespace }}
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Resource Group if not exists
        run: |
          az group create \
            --name "$RESOURCE_GROUP" \
            --location "$AZURE_LOCATION"
          echo "Resource group '$RESOURCE_GROUP' ensured."

      - name: Create Azure Container Apps Environment
        run: |
          az containerapp env create \
            --name "$CONTAINERAPPS_ENVIRONMENT" \
            --resource-group "$RESOURCE_GROUP" \
            --location "$AZURE_LOCATION"
          echo "Azure Container Apps Environment provisioned."

      - name: Create Azure Service Bus Namespace
        run: |
          az servicebus namespace create \
            --name "$SERVICEBUS_NAMESPACE" \
            --resource-group "$RESOURCE_GROUP" \
            --location "$AZURE_LOCATION" \
            --sku Standard
          echo "Azure Service Bus Namespace '$SERVICEBUS_NAMESPACE' provisioned."

      - name: Set workflow outputs
        id: set-outputs
        run: |
          echo "resource_group=$RESOURCE_GROUP" >> $GITHUB_OUTPUT
          echo "containerapps_env=$CONTAINERAPPS_ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "azure_location=$AZURE_LOCATION" >> $GITHUB_OUTPUT
          echo "servicebus_namespace=$SERVICEBUS_NAMESPACE" >> $GITHUB_OUTPUT

  call-eventmanagement-infra:
    needs: deploy-shared-infra
    uses: ./.github/workflows/Domain_EventManagement_Infra.yml
    with:
      resource_group: ${{ needs.deploy-shared-infra.outputs.resource_group }}
      containerapps_env: ${{ needs.deploy-shared-infra.outputs.containerapps_env }}
      azure_location: ${{ needs.deploy-shared-infra.outputs.azure_location }}
      servicebus_namespace: ${{ needs.deploy-shared-infra.outputs.servicebus_namespace }}
      managed_identity_name: acmetickets-eventmgmt-mi
      container_app_name: acmetickets-eventmgmt-api


