name: Event Management Infrastructure

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Azure Resource Group'
        required: true
        type: string
        default: acmetickets-rg
      containerapps_env:
        description: 'Azure Container Apps Environment'
        required: true
        type: string
        default: acmeticketsacadev
      azure_location:
        description: 'Azure Region'
        required: true
        type: string
        default: eastus2
      servicebus_namespace:
        description: 'Azure Service Bus Namespace'
        required: true
        type: string
        default: acmeticketsasb
      managed_identity_name:
        description: 'User Assigned Managed Identity Name'
        required: true
        type: string
        default: acmetickets-eventmgmt-mi
      container_api_name:
        description: 'Azure Container API App Name'
        required: true
        type: string
        default: eventmgmt-api
      container_message_app_name:
        description: 'Azure Container Message App Name'
        required: true
        type: string
        default: eventmgmt-msg

  workflow_call:
    inputs:
      resource_group:
        description: 'Azure Resource Group'
        required: true
        type: string
      containerapps_env:
        description: 'Azure Container Apps Environment'
        required: true
        type: string
      azure_location:
        description: 'Azure Region'
        required: true
        type: string
      servicebus_namespace:
        description: 'Azure Service Bus Namespace'
        required: true
        type: string
      managed_identity_name:
        description: 'User Assigned Managed Identity Name'
        required: true
        type: string
      container_api_name:
        description: 'Azure Container API App Name'
        required: true
        type: string
      container_message_app_name:
        description: 'Azure Container Message App Name'
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
        
permissions:
    contents: read
    id-token: write # Required to fetch an OIDC token for Azure login.
    actions: write # Required to use the Azure login action.

jobs:
  deploy-container-app:
    runs-on: ubuntu-latest 
    env:
      RESOURCE_GROUP: ${{ inputs.resource_group }}
      CONTAINERAPPS_ENVIRONMENT: ${{ inputs.containerapps_env }}
      AZURE_LOCATION: ${{ inputs.azure_location }}
      SERVICEBUS_NAMESPACE: ${{ inputs.servicebus_namespace }}
      MANAGED_IDENTITY_NAME: ${{ inputs.managed_identity_name }}
      CONTAINER_API_NAME: ${{ inputs.container_api_name }}
      CONTAINER_MESSAGE_APP_NAME: ${{ inputs.container_message_app_name }}
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Ensure Managed Identity exists and get Resource ID and Principal ID
      - name: Ensure Managed Identity exists and get Resource ID
        id: mi
        run: |
          MI_ID=$(az identity show --name "$MANAGED_IDENTITY_NAME" --resource-group "$RESOURCE_GROUP" --query id -o tsv 2>/dev/null || true)
          MI_PRINCIPAL_ID=$(az identity show --name "$MANAGED_IDENTITY_NAME" --resource-group "$RESOURCE_GROUP" --query principalId -o tsv 2>/dev/null || true)
          if [ -z "$MI_ID" ]; then
            az identity create --name "$MANAGED_IDENTITY_NAME" --resource-group "$RESOURCE_GROUP"
            MI_ID=$(az identity show --name "$MANAGED_IDENTITY_NAME" --resource-group "$RESOURCE_GROUP" --query id -o tsv)
            MI_PRINCIPAL_ID=$(az identity show --name "$MANAGED_IDENTITY_NAME" --resource-group "$RESOURCE_GROUP" --query principalId -o tsv)
            echo "Created managed identity: $MANAGED_IDENTITY_NAME"
          else
            echo "Managed identity already exists: $MANAGED_IDENTITY_NAME"
          fi
          echo "id=$MI_ID" >> $GITHUB_OUTPUT
          echo "principal_id=$MI_PRINCIPAL_ID" >> $GITHUB_OUTPUT

      - name: Get Service Bus Namespace Resource ID
        id: sb
        run: |
          SB_ID=$(az servicebus namespace show --name "$SERVICEBUS_NAMESPACE" --resource-group "$RESOURCE_GROUP" --query id -o tsv)
          echo "id=$SB_ID" >> $GITHUB_OUTPUT

      - name: Assign Service Bus Data Sender role to Managed Identity
        run: |
          az role assignment create \
            --assignee-object-id ${{ steps.mi.outputs.principal_id }} \
            --assignee-principal-type ServicePrincipal \
            --role "Azure Service Bus Data Sender" \
            --scope ${{ steps.sb.outputs.id }}

      - name: Assign Service Bus Data Receiver role to Managed Identity
        run: |
          az role assignment create \
            --assignee-object-id ${{ steps.mi.outputs.principal_id }} \
            --assignee-principal-type ServicePrincipal \
            --role "Azure Service Bus Data Receiver" \
            --scope ${{ steps.sb.outputs.id }}

      - name: Check if Azure Container App exists
        id: check_aca
        run: |
          result=$(az containerapp show --name "$CONTAINER_API_NAME" --resource-group "$RESOURCE_GROUP" --query "name" --output tsv 2>/dev/null || echo "notfound")
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Create API App
        if: ${{ steps.check_aca.outputs.result == 'notfound' }}
        run: |
          az containerapp create \
            --name "$CONTAINER_API_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --environment "$CONTAINERAPPS_ENVIRONMENT" \
            --ingress external

      # Check if Azure Container Message App exists
      - name: Check if Azure Container Message App exists
        id: check_msg_aca
        run: |
          result=$(az containerapp show --name "$CONTAINER_MESSAGE_APP_NAME" --resource-group "$RESOURCE_GROUP" --query "name" --output tsv 2>/dev/null || echo "notfound")
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Create Message App
        if: ${{ steps.check_msg_aca.outputs.result == 'notfound' }}
        run: |
          az containerapp create \
            --name "$CONTAINER_MESSAGE_APP_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --environment "$CONTAINERAPPS_ENVIRONMENT" \
            --ingress external

      # EventManagement API
      - name: Create Azure Service Bus Queue for NServiceBus Endpoint EventManagement.Api
        run: |
          set -e
          az servicebus queue create \
            --resource-group "$RESOURCE_GROUP" \
            --namespace-name "$SERVICEBUS_NAMESPACE" \
            --name EventManagement.Api
          echo "Azure Service Bus Queue 'EventManagement.Api' provisioned."

      # EventManagement Message
      - name: Create Azure Service Bus Queue for NServiceBus Endpoint EventManagement.Message
        run: |
          set -e
          az servicebus queue create \
            --resource-group "$RESOURCE_GROUP" \
            --namespace-name "$SERVICEBUS_NAMESPACE" \
            --name EventManagement.Message
          echo "Azure Service Bus Queue 'EventManagement.Message' provisioned."

      - name: Create Azure Service Bus Topic for TicketRequestedEvent
        run: |
          set -e
          az servicebus topic create \
            --resource-group "$RESOURCE_GROUP" \
            --namespace-name "$SERVICEBUS_NAMESPACE" \
            --name AcmeTickets.EventManagement.InternalContracts.Events.TicketRequestedEvent
          echo "Azure Service Bus Topic 'AcmeTickets.EventManagement.InternalContracts.Events.TicketRequestedEvent' provisioned."

      # Create Azure CosmosDB instance for EventManagement (lowest paid tier)
      - name: Create Azure CosmosDB Account for EventManagementDb
        run: |
          set -e
          az cosmosdb create \
            --name eventmanagementdb \
            --resource-group "$RESOURCE_GROUP" \
            --locations regionName="$AZURE_LOCATION" failoverPriority=0 isZoneRedundant=False \
            --default-consistency-level Session \
            --kind GlobalDocumentDB
          echo "Azure CosmosDB Account 'eventmanagementdb' provisioned with default (lowest) tier."

      - name: Create CosmosDB Database and Collection for Events
        run: |
          set -e
          az cosmosdb sql database create \
            --account-name eventmanagementdb \
            --resource-group "$RESOURCE_GROUP" \
            --name EventManagement
          az cosmosdb sql container create \
            --account-name eventmanagementdb \
            --resource-group "$RESOURCE_GROUP" \
            --database-name EventManagement \
            --name Events \
            --partition-key-path "/id"
          echo "CosmosDB Collection 'Events' created in database 'EventManagement'."

      # Grant Cosmos DB access to Managed Identity
      - name: Assign Cosmos DB Built-in Data Contributor role to Managed Identity
        run: |
          set -e
          COSMOSDB_ID=$(az cosmosdb show --name eventmanagementdb --resource-group "$RESOURCE_GROUP" --query id -o tsv)
          az cosmosdb sql role assignment create \
            --account-name eventmanagementdb \
            --resource-group "$RESOURCE_GROUP" \
            --role-definition-id "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.DocumentDB/databaseAccounts/eventmanagementdb/sqlRoleDefinitions/00000000-0000-0000-0000-000000000002" \
            --principal-id ${{ steps.mi.outputs.principal_id }} \
            --scope "$COSMOSDB_ID"
          echo "Assigned 'Cosmos DB Built-in Data Contributor' role to managed identity for Cosmos DB."