name: Publish NuGet Package

permissions:
  contents: read
  packages: write

on:
  push:
    paths:
      - 'src/Contracts/Public/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Contracts/Public/PublicContracts.csproj

      - name: Build
        run: dotnet build --configuration Release src/Contracts/Public/PublicContracts.csproj

      - name: Pack
        run: dotnet pack --configuration Release src/Contracts/Public/PublicContracts.csproj --output ./nupkg

      - name: Add GitHub Packages source
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
